/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config dist/server/wrangler.json --include-runtime false --include-env true` (hash: 923c31b2987da7e9a95e81ba5c94e782)
interface __BaseEnv_Env {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
