export type PolicyCatalogEntry = {
  id: string;
  institution: string;
  country: string;
  region: "Egypt" | "Gulf" | "United States" | "International";
  scale: string;
  scope: string;
  catalogLabel: string;
  catalogUrl: string;
  policyLabel: string;
  policyUrl: string;
  reviewedAt: string;
  rules: Array<{
    type: "grading" | "retake" | "withdrawal" | "transfer" | "degree";
    summary: string;
    confidence: "official_verified" | "official_program_specific";
  }>;
};

export const POLICY_CATALOG: PolicyCatalogEntry[] = [
  {
    id: "aastmt",
    institution: "Arab Academy for Science, Technology and Maritime Transport (AASTMT)",
    country: "Egypt",
    region: "Egypt",
    scale: "4.0 · college-specific boundaries",
    scope: "College and programme rules vary; the selected regulation and catalog year control.",
    catalogLabel: "AASTMT academic regulations",
    catalogUrl: "https://aast.edu/en/colleges/coe/smartvillage/contenttemp.php?page_id=41900013",
    policyLabel: "AASTMT Education and Study Regulations",
    policyUrl: "https://www.aast.edu/en/openfiles/opencmsfiles/pdf_retreive_cms.php?disp_unit=388%2FEducation-Regulations+%281%29.pdf",
    reviewedAt: "2026-07-30",
    rules: [
      { type: "grading", summary: "GPA is credit weighted on a 0–4 scale; percentage and conditional-pass boundaries can differ by college.", confidence: "official_program_specific" },
      { type: "retake", summary: "Failed core courses must be repeated; published regulations cap the improved grade and distinguish semester from cumulative treatment.", confidence: "official_program_specific" },
      { type: "withdrawal", summary: "Withdrawal timing and financial conditions depend on the applicable college regulation.", confidence: "official_program_specific" },
    ],
  },
  {
    id: "cairo-university",
    institution: "Cairo University",
    country: "Egypt",
    region: "Egypt",
    scale: "Faculty-specific credit and grading systems",
    scope: "Cairo University faculties publish separate programme bylaws; no universal GPA preset is applied.",
    catalogLabel: "Cairo University official portal",
    catalogUrl: "https://cu.edu.eg/Home",
    policyLabel: "Faculty of Mass Communication student guide",
    policyUrl: "https://masscomm.cu.edu.eg/AdminDepartmentFiles/EMCCU%20Student%20Guide%202023%C2%A4eng.heba%C2%A42024-5-30%20%209-39-30-161.pdf",
    reviewedAt: "2026-07-30",
    rules: [
      { type: "degree", summary: "Programme credit totals and study duration are faculty-specific and must be read from the applicable student guide.", confidence: "official_program_specific" },
      { type: "transfer", summary: "Transfer conditions and credit recognition are faculty- and programme-controlled.", confidence: "official_program_specific" },
    ],
  },
  {
    id: "auc",
    institution: "The American University in Cairo",
    country: "Egypt",
    region: "Egypt",
    scale: "4.0",
    scope: "Undergraduate academic requirements and the active catalog year.",
    catalogLabel: "AUC academic catalog",
    catalogUrl: "https://catalog.aucegypt.edu/",
    policyLabel: "AUC undergraduate academic requirements",
    policyUrl: "https://www1.aucegypt.edu/catalog/undergrad/acadreq/acadreq.html",
    reviewedAt: "2026-07-30",
    rules: [
      { type: "retake", summary: "The published course-repeat policy permits one repeat for specified low grades, subject to limits and conditions.", confidence: "official_verified" },
      { type: "withdrawal", summary: "Withdrawal notation, deadlines, and academic consequences must be checked in the current catalog.", confidence: "official_verified" },
      { type: "transfer", summary: "Transfer credit requires official pre-approval and university review.", confidence: "official_verified" },
    ],
  },
  {
    id: "king-saud-university",
    institution: "King Saud University",
    country: "Saudi Arabia",
    region: "Gulf",
    scale: "5.0",
    scope: "General university scale with programme-level progression requirements.",
    catalogLabel: "KSU regulations of study and examinations",
    catalogUrl: "https://engineering.ksu.edu.sa/sites/engineering.ksu.edu.sa/files/imce_images/regulations_of_study_and_examinations_of_ksu.pdf",
    policyLabel: "KSU GPA formula and academic system",
    policyUrl: "https://sciences.ksu.edu.sa/en/node/9701",
    reviewedAt: "2026-07-30",
    rules: [
      { type: "grading", summary: "The official 5.0 scale assigns A+ 5.00 through F 1.00 and weights grade points by credit hours.", confidence: "official_verified" },
      { type: "degree", summary: "Programme handbooks may impose course and progression grades beyond the general GPA scale.", confidence: "official_program_specific" },
    ],
  },
  {
    id: "uaeu",
    institution: "United Arab Emirates University",
    country: "United Arab Emirates",
    region: "Gulf",
    scale: "4.0",
    scope: "General undergraduate quality-point policy; programme rules can add requirements.",
    catalogLabel: "UAEU current catalog",
    catalogUrl: "https://www.uaeu.ac.ae/en/catalog/",
    policyLabel: "UAEU grades and grading policy",
    policyUrl: "https://www.uaeu.ac.ae/en/about/policies/admissions_and_enrollment/pol-ae_04_en.pdf",
    reviewedAt: "2026-07-30",
    rules: [
      { type: "grading", summary: "Semester and cumulative GPA use credit-weighted quality points on a 4.00 scale.", confidence: "official_verified" },
      { type: "degree", summary: "Graduation also depends on programme credits and completion rules, not GPA alone.", confidence: "official_verified" },
    ],
  },
  {
    id: "qatar-university",
    institution: "Qatar University",
    country: "Qatar",
    region: "Gulf",
    scale: "4.0 · programme-specific rules",
    scope: "2025–2026 undergraduate catalog and current registration calendar.",
    catalogLabel: "Qatar University undergraduate catalog 2025–2026",
    catalogUrl: "https://qttsc.qu.edu.qa/en-us/students/documents/undergraduate-student-catalog-2025-2026-en.pdf",
    policyLabel: "Qatar University registration guide",
    policyUrl: "https://www.qu.edu.qa/en-us/students/Documents/Registration-Guide-2024-2025-Final.pdf",
    reviewedAt: "2026-07-30",
    rules: [
      { type: "withdrawal", summary: "Semester and university withdrawal must follow the academic-calendar deadline and registration process.", confidence: "official_verified" },
      { type: "degree", summary: "Course descriptions and degree requirements are published in the undergraduate catalog.", confidence: "official_verified" },
    ],
  },
  {
    id: "kuwait-university",
    institution: "Kuwait University",
    country: "Kuwait",
    region: "Gulf",
    scale: "Credit-unit system · college-specific grading",
    scope: "University credit-system bylaw plus the applicable college handbook.",
    catalogLabel: "Kuwait University credit system bylaw",
    catalogUrl: "https://www.ku.edu.kw/sites/default/files/2024-11/kuw118669.pdf",
    policyLabel: "Kuwait University admission, registration and transfer regulations",
    policyUrl: "https://ahs.ku.edu.kw/sites/default/files/2024-10/11%20ART%20Regulations.pdf",
    reviewedAt: "2026-07-30",
    rules: [
      { type: "degree", summary: "Degree completion is organized through a credit-unit system with prerequisite and adviser controls.", confidence: "official_verified" },
      { type: "transfer", summary: "Transfer admission and recognized-credit rules are controlled by the university and receiving college.", confidence: "official_program_specific" },
    ],
  },
  {
    id: "sultan-qaboos-university",
    institution: "Sultan Qaboos University",
    country: "Oman",
    region: "Gulf",
    scale: "4.0 · college and programme rules",
    scope: "Undergraduate academic regulations and the applicable college bulletin.",
    catalogLabel: "SQU undergraduate academic regulations",
    catalogUrl: "https://www.squ.edu.om/Portals/24/academic-en-2019_1.pdf",
    policyLabel: "SQU academic advising handbook",
    policyUrl: "https://www.squ.edu.om/Portals/10/Academic%20Advising%20Student%20Handbook%20%28E%29.pdf",
    reviewedAt: "2026-07-30",
    rules: [
      { type: "withdrawal", summary: "Official withdrawal and temporary postponement require the university process and are recorded on the academic record.", confidence: "official_verified" },
      { type: "retake", summary: "Repeat eligibility and its GPA treatment depend on the applicable programme regulations.", confidence: "official_program_specific" },
    ],
  },
  {
    id: "ucla",
    institution: "University of California, Los Angeles",
    country: "United States",
    region: "United States",
    scale: "4.0",
    scope: "Registrar grading and repetition policies.",
    catalogLabel: "UCLA General Catalog",
    catalogUrl: "https://catalog.registrar.ucla.edu/",
    policyLabel: "UCLA Registrar grades policy",
    policyUrl: "https://catalog.registrar.ucla.edu/Policies-and-Regulations/Academic-Policies/Grades",
    reviewedAt: "2026-07-30",
    rules: [
      { type: "grading", summary: "Grade points are assigned per unit; Passed grades do not add grade points to GPA.", confidence: "official_verified" },
      { type: "retake", summary: "Repetition treatment changes after the published unit threshold.", confidence: "official_verified" },
    ],
  },
  {
    id: "ut-austin",
    institution: "The University of Texas at Austin",
    country: "United States",
    region: "United States",
    scale: "4.0",
    scope: "Registrar grade symbols and GPA guidance; Law is outside the general calculator.",
    catalogLabel: "UT Austin catalog",
    catalogUrl: "https://catalog.utexas.edu/",
    policyLabel: "UT Austin Registrar grade symbols",
    policyUrl: "https://registrar.utexas.edu/faculty/grades/symbols",
    reviewedAt: "2026-07-30",
    rules: [
      { type: "grading", summary: "The Registrar publishes authorized plus/minus grade symbols and quality points.", confidence: "official_verified" },
      { type: "degree", summary: "The general GPA calculator is not an official University GPA and excludes Law grading.", confidence: "official_verified" },
    ],
  },
  {
    id: "universiti-malaya",
    institution: "Universiti Malaya",
    country: "Malaysia",
    region: "International",
    scale: "4.0",
    scope: "Bachelor's degree regulations; faculty and degree-level schemes can differ.",
    catalogLabel: "UM Faculty of Science handbook 2025–2026",
    catalogUrl: "https://ebook.um.edu.my/fsains/FINAL_HANDBOOK_20252026/files/basic-html/page13.html",
    policyLabel: "UM Bachelor's Degree Regulations 2024",
    policyUrl: "https://fsktm.um.edu.my/fsktm/doc/undergraduate/KaedahPeraturan/UM%20%28Bachelor%27s%20Degree%29%20Regulations%202024_final_Senate%2026.09.24.pdf",
    reviewedAt: "2026-07-30",
    rules: [
      { type: "grading", summary: "The published bachelor's scheme uses a 4.00 maximum and programme-specific pass requirements.", confidence: "official_verified" },
      { type: "degree", summary: "Foundation, bachelor's and postgraduate schemes must not be mixed.", confidence: "official_program_specific" },
    ],
  },
  {
    id: "mit",
    institution: "Massachusetts Institute of Technology",
    country: "United States",
    region: "United States",
    scale: "5.0",
    scope: "MIT undergraduate grading, units, repeats, and transfer-credit treatment.",
    catalogLabel: "MIT academic performance and grades",
    catalogUrl: "https://catalog.mit.edu/mit/procedures/academic-performance-grades/",
    policyLabel: "MIT academic performance and grades",
    policyUrl: "https://catalog.mit.edu/mit/procedures/academic-performance-grades/",
    reviewedAt: "2026-08-08",
    rules: [
      { type: "grading", summary: "MIT reports term and cumulative ratings on a 5.0 scale using subject units and assigned grade points.", confidence: "official_verified" },
      { type: "retake", summary: "When a subject is repeated, each grade remains in the GPA record while the units count once toward rate-of-progress requirements.", confidence: "official_verified" },
      { type: "transfer", summary: "Approved transfer credit carries units but no MIT grade and does not enter the MIT GPA.", confidence: "official_verified" },
      { type: "withdrawal", summary: "A subject dropped by the published deadline is not used in GPA calculations.", confidence: "official_verified" },
    ],
  },
  {
    id: "unsw",
    institution: "UNSW Sydney",
    country: "Australia",
    region: "International",
    scale: "WAM · percentage marks, not a universal GPA",
    scope: "UNSW official grade definitions and weighted-average-mark calculation.",
    catalogLabel: "UNSW results and grades",
    catalogUrl: "https://www.student.unsw.edu.au/grades",
    policyLabel: "UNSW weighted average mark",
    policyUrl: "https://www.student.unsw.edu.au/wam",
    reviewedAt: "2026-08-08",
    rules: [
      { type: "grading", summary: "UNSW uses marks and grade symbols and states that it does not calculate a GPA; WAM is the primary weighted result.", confidence: "official_verified" },
      { type: "degree", summary: "WAM multiplies each eligible course mark by its units of credit and divides by the eligible units attempted.", confidence: "official_verified" },
      { type: "transfer", summary: "Transfer-credit and non-graded results require the official WAM inclusion rules rather than a generic GPA conversion.", confidence: "official_verified" },
    ],
  },
  {
    id: "ubc",
    institution: "The University of British Columbia",
    country: "Canada",
    region: "International",
    scale: "Percentage and letter grades",
    scope: "UBC grading practices plus faculty- and programme-specific academic standing rules.",
    catalogLabel: "UBC grades and standing",
    catalogUrl: "https://students.ubc.ca/enrolment/courses/grades/",
    policyLabel: "UBC satisfactory academic progress",
    policyUrl: "https://students.ubc.ca/wp-content/uploads/ubc_satisfactory_academic_progress_undergrads.pdf",
    reviewedAt: "2026-08-08",
    rules: [
      { type: "grading", summary: "UBC publishes percentage and letter-grade relationships; faculty rules determine how averages and standing are applied.", confidence: "official_verified" },
      { type: "retake", summary: "Repeated and failed courses remain subject to faculty progression and satisfactory-progress requirements.", confidence: "official_program_specific" },
      { type: "withdrawal", summary: "Withdrawal notation and academic-progress effects follow the current UBC calendar and faculty rules.", confidence: "official_program_specific" },
    ],
  },
  {
    id: "oxford",
    institution: "University of Oxford",
    country: "United Kingdom",
    region: "International",
    scale: "Programme-specific marks and degree classifications",
    scope: "University assessment framework plus the examination regulations for the student's course.",
    catalogLabel: "Oxford student handbook",
    catalogUrl: "https://www.ox.ac.uk/students/academic/student-handbook",
    policyLabel: "Oxford examiners and assessment framework",
    policyUrl: "https://governance.admin.ox.ac.uk/education-committee/policies/examiners-assessment-framework",
    reviewedAt: "2026-08-08",
    rules: [
      { type: "grading", summary: "Oxford does not use one university-wide GPA scale; marks, conventions, and classifications depend on the examination and programme.", confidence: "official_program_specific" },
      { type: "retake", summary: "Resit eligibility and the result that can be awarded are controlled by the applicable examination regulations.", confidence: "official_program_specific" },
      { type: "degree", summary: "Final classification must be evaluated using the course's published conventions rather than a generic GPA conversion.", confidence: "official_program_specific" },
    ],
  },
  {
    id: "nus",
    institution: "National University of Singapore",
    country: "Singapore",
    region: "International",
    scale: "5.0",
    scope: "NUS academic structure, grading, S/U, withdrawal, and unit-weighted GPA rules.",
    catalogLabel: "NUS academic structure and grading",
    catalogUrl: "https://nus.edu.sg/registrar/academic-information-policies/academic-structure-grading",
    policyLabel: "NUS academic structure and grading",
    policyUrl: "https://nus.edu.sg/registrar/academic-information-policies/academic-structure-grading",
    reviewedAt: "2026-08-08",
    rules: [
      { type: "grading", summary: "NUS GPA is the unit-weighted average of grade points on a 5.0 scale.", confidence: "official_verified" },
      { type: "withdrawal", summary: "Withdrawal timing determines whether a module is removed, shown with a withdrawal grade, or receives an academic penalty.", confidence: "official_verified" },
      { type: "degree", summary: "Satisfactory/Unsatisfactory results are excluded from GPA but remain governed by programme and S/U-option limits.", confidence: "official_verified" },
    ],
  },
  {
    id: "king-abdulaziz-university",
    institution: "King Abdulaziz University",
    country: "Saudi Arabia",
    region: "Gulf",
    scale: "5.0",
    scope: "General undergraduate study and examination regulations plus college-specific requirements.",
    catalogLabel: "KAU academic regulations",
    catalogUrl: "https://www.kau.edu.sa/en/regulation/762ed3bf-8746-486f-b319-c8a0abfd313e",
    policyLabel: "KAU undergraduate study and examination regulations",
    policyUrl: "https://kau.edu.sa/web/static?path=uploads%2F2025%2FSep%2Fmediacenter%2FRegulations_and_Policies%2Fk9frh8gg0B0mkhyl.pdf",
    reviewedAt: "2026-08-08",
    rules: [
      { type: "grading", summary: "The official undergraduate regulations define a 5.0 grade-point scale and credit-weighted semester and cumulative averages.", confidence: "official_verified" },
      { type: "retake", summary: "Course repetition and progression consequences must follow the current university regulation and college plan.", confidence: "official_program_specific" },
      { type: "degree", summary: "Graduation requires the programme curriculum and the university's cumulative-average and residency conditions.", confidence: "official_program_specific" },
    ],
  },
  {
    id: "university-of-toronto",
    institution: "University of Toronto",
    country: "Canada",
    region: "International",
    scale: "4.0 · faculty-specific rules",
    scope: "Faculty of Arts & Science grading and degree rules; other divisions publish separate calendars.",
    catalogLabel: "U of T Arts & Science academic calendar",
    catalogUrl: "https://artsci.calendar.utoronto.ca/",
    policyLabel: "U of T Arts & Science grading regulations",
    policyUrl: "https://artsci.calendar.utoronto.ca/print/pdf/node/15/debug",
    reviewedAt: "2026-08-08",
    rules: [
      { type: "grading", summary: "Arts & Science publishes percentage, letter-grade, and grade-point relationships on a 4.0 scale.", confidence: "official_program_specific" },
      { type: "degree", summary: "Degree and cumulative-GPA requirements depend on the student's faculty, programme combination, and calendar year.", confidence: "official_program_specific" },
      { type: "withdrawal", summary: "Credit/No Credit and late-withdrawal treatment must follow the faculty calendar and deadlines.", confidence: "official_program_specific" },
    ],
  },
];

export const POLICY_DATA_SOURCES = [
  {
    label: "U.S. Department of Education — College Scorecard API",
    url: "https://collegescorecard.ed.gov/data/api-documentation/",
    purpose: "Institution, programme, cost, completion and earnings context for U.S. planning.",
  },
  {
    label: "European Commission — ECTS",
    url: "https://education.ec.europa.eu/education-levels/higher-education/inclusive-and-connected-higher-education/european-credit-transfer-and-accumulation-system",
    purpose: "Official ECTS purpose and mobility guidance.",
  },
  {
    label: "QAA — Higher Education Credit Framework for England",
    url: "https://www.qaa.ac.uk/docs/qaa/quality-code/higher-education-credit-framework-for-england.pdf",
    purpose: "UK credit and ECTS comparison guidance.",
  },
];
